### ISSUE TITLE
not support @keyframes animation of SVG?

### ISSUE THREAD

**Issue by veelion** [canvg/canvg#699]
I test an SVG file with @keyframes animation on the test page: 

http://canvg.github.io/canvg/examples/index.htm

but the js throw errors about matchesSelector:
`Uncaught DOMException: Failed to execute 'matches' on 'Element': '77%' is not a valid selector.
    at matchesSelector (http://canvg.github.io/canvg/dist/browser/canvg.js:124:20)
    at svg.Element.path.addStylesFromStyleDefinition (http://canvg.github.io/canvg/dist/browser/canvg.js:934:36)
    at svg.Element.path.svg.Element.ElementBase (http://canvg.github.io/canvg/dist/browser/canvg.js:970:13)
    at svg.Element.path.svg.Element.RenderedElementBase (http://canvg.github.io/canvg/dist/browser/canvg.js:1008:11)
    at svg.Element.path.svg.Element.PathElementBase (http://canvg.github.io/canvg/dist/browser/canvg.js:1109:11)
    at new svg.Element.path (http://canvg.github.io/canvg/dist/browser/canvg.js:1417:11)
    at Object.svg.CreateElement (http://canvg.github.io/canvg/dist/browser/canvg.js:3833:12)
    at svg.Element.g.addChild (http://canvg.github.io/canvg/dist/browser/canvg.js:926:32)
    at svg.Element.g.svg.Element.ElementBase (http://canvg.github.io/canvg/dist/browser/canvg.js:995:44)
    at svg.Element.g.svg.Element.RenderedElementBase (http://canvg.github.io/canvg/dist/browser/canvg.js:1008:11)`

the SVG file is:
https://raw.githubusercontent.com/skishore/makemeahanzi/master/svgs/19970.svg

**Comment by gabelerner** [comment]
unfortunately, most css will never be supported per https://github.com/canvg/canvg/issues/671. if you want animations, you can use the animation tag similar to http://canvg.github.io/canvg/examples/index.htm?svg=../svgs/1.svg
