### ISSUE TITLE
feColorMatrix causes error in the console + blank canvas

### ISSUE THREAD

**Issue by jimousse** [canvg/canvg#721]
Hi!

The issue is probably related to #241 but it is closed so I'm opening a new one to give some new steps to reproduce.

Here's the `svg` that I'm trying to render on `canvas`:
```
<svg xmlns="http://www.w3.org/2000/svg" direction="ltr" viewbox="0 0 100 100" width="100" height="100" style="vertical-align: top;">
	<defs>
	   <g>
		  <filter id="myFilter" filterUnits="objectBoundingBox">
			 <feColorMatrix type="matrix" values="1 2 3 4 5, 0 1 0 0 0, 0 0 1 0 0, 0 0 0 1 0"/>
		  </filter>
	   </g>
	</defs>
	<g transform="translate(-320,30)">
	   <path d="M4.51351666838205,0A4.51351666838205,4.51351666838205,0,1,1,-4.51351666838205,0A4.51351666838205,4.51351666838205,0,1,1,4.51351666838205,0" transform="translate(348.75,23.285714285714306) scale(1)" fill="hsl(207,59%,56%)" stroke="hsl(207,59%,56%)" stroke-width="1" filter="url(#myFilter)" fill-opacity="0.4" stroke-opacity="1"/>
	</g>
 </svg>
```

On the hosted demo page: http://canvg.github.io/canvg/examples/index.htm

![image](https://user-images.githubusercontent.com/6637867/60272015-a7ba7380-98f3-11e9-86b5-de5cfe20c958.png)

I get the following error:
```
canvg.js:3764 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at svg.Element.feColorMatrix.apply (http://canvg.github.io/canvg/dist/browser/canvg.js:3764:26)
    at svg.Element.filter.apply (http://canvg.github.io/canvg/dist/browser/canvg.js:3665:29)
    at svg.Element.path.render (http://canvg.github.io/canvg/dist/browser/canvg.js:898:37)
    at svg.Element.g.renderChildren (http://canvg.github.io/canvg/dist/browser/canvg.js:920:27)
    at svg.Element.g.render (http://canvg.github.io/canvg/dist/browser/canvg.js:901:15)
    at svg.Element.svg.renderChildren (http://canvg.github.io/canvg/dist/browser/canvg.js:920:27)
    at svg.Element.svg.render (http://canvg.github.io/canvg/dist/browser/canvg.js:901:15)
    at draw (http://canvg.github.io/canvg/dist/browser/canvg.js:3945:10)
    at Object.svg.loadXmlDoc (http://canvg.github.io/canvg/dist/browser/canvg.js:3955:8)
    at Object.svg.loadXml (http://canvg.github.io/canvg/dist/browser/canvg.js:3853:10)
apply @ canvg.js:3764
apply @ canvg.js:3665
render @ canvg.js:898
renderChildren @ canvg.js:920
render @ canvg.js:901
renderChildren @ canvg.js:920
render @ canvg.js:901
draw @ canvg.js:3945
svg.loadXmlDoc @ canvg.js:3955
svg.loadXml @ canvg.js:3853
canvg @ canvg.js:112
render @ index.htm:64
renderCustom @ index.htm:82
onclick @ index.htm:304
```

When I remove `filter="url(#myFilter)"` in my `path`, it renders fine:

![image](https://user-images.githubusercontent.com/6637867/60272164-f1a35980-98f3-11e9-949c-970110930ee4.png)

Any idea why this happens ?

Thanks!

**Comment by gabelerner** [comment]
related to https://github.com/canvg/canvg/issues/667

canvg doesn't do great at bounding boxes and thinks your path height is 0 which is why it breaks on getting the context

something simpler like
```xml
<svg xmlns="http://www.w3.org/2000/svg" direction="ltr" viewbox="0 0 100 100" width="100" height="100" style="vertical-align: top;">
	<defs>
		  <filter id="myFilter" filterUnits="objectBoundingBox">
			 <feColorMatrix type="matrix" values="1 2 3 4 5, 0 1 0 0 0, 0 0 1 0 0, 0 0 0 1 0"/>
		  </filter>
	</defs>
	<g>
	   <path d="M 10 10 H 90 V 90 H 10 L 10 10" fill="green" filter="url(#myFilter)" />
	</g>
 </svg>
```

will work. if you remove the filter you get a green box, with the filter it's orange. gonna close out this issue as it's lumped into that main thread for others to fix.
